### ISSUE TITLE
recog3: replace university with institution

### ISSUE THREAD

**Issue by StephanJanosch** [softwaresaved/international-survey#176]
The person answering might not work at a university. Maybe replace with a more generic term.

**Comment by Oliph** [comment]
Fixed: 9359de9e59875e393f76ce283fce2c861e6f827b

**Comment by Oliph** [comment]
The origin of this question is because during the others years we failed to get information about who gives feedback and who failed. We have the hypothesis that RSE work is recognised by peers and by supervisors but less at a higher level. Here we wanted to see if the feedback were good at supervisor/colleagues levels and different at a higher level. 

Right now I don't have a clear solution for the wording but I agree with you that it is not ideal. 

Is anyone have a suggestion?
