### ISSUE TITLE
Does it make sense to integrate perfCheck5 again?

### ISSUE THREAD

**Issue by mrtnhmtz** [softwaresaved/international-survey#181]
perfCheck5 "Does your work provide you with direct feedback on how well you are doing your work?" seems to be not covered any more. Would it make sense to integrate question(s) on whether and how feedback is provided?

**Comment by Oliph** [comment]
We can add it back. However, the constant complain was about these questions being too vague for the participants and because the reasons why we included in the first place was not relevant anymore. 

However, if you have an interest in that question, we can add it back for your survey. Just tell me if I include it again or not.

**Comment by Oliph** [comment]
Closed: Don't seem to raise interest anymore
