### ISSUE TITLE
An in-depth test run should be performed based on some sort of pre-final version

### ISSUE THREAD

**Issue by mrtnhmtz** [softwaresaved/international-survey#215]
- [x] Apply styling of hrefs in the welcome message, so that they are identified as clickable links
- [x] train3 doesn't show up because the condition does not fit any more
- [x] recog3 still doesn't make sense: Who is "the university"? Management? Internal evaluation procedures?
- [x] currentEmp11 should be shown only when currentEmp10 is not "permanent"
- [x] prevEmp1 is a single question without asking for further details, i.e. presenting questions prevEmp2 to prevEmp24de ... is this intended
- [x] open1can is not presented in the answer matrix together with open2de and open3can
- [x] turnOver6 is not presented in the answer matrix together with percEmp1 to progRSE5
- [x] Its not checked yet if a question is mandatory and must be filled (so it also cannot be checked if questions are flagged properly)
- [x] socio4 uses GBP, but I remember that we had "translations" for other currencies in 2017, how do we continue?
- [x] Does edu2 require an option "other" in the answers?
- [x] A "Back" button is missing

The problem described before in one of the emails that empty pages are shown occurred once again and presented following error message:
`CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column '421498X1345X77778' in 'field list'`

**Comment by StephanJanosch** [comment]
- [ ] conf2Can does not appear when selected Yes in conf1can (german version)

**Comment by mrtnhmtz** [comment]
Wrt socio4, in 2017 we already addressed the GBP, EUR currencies, see https://github.com/softwaresaved/international-survey/blob/master/survey_creation/2017/de/listAnswers/salary.csv

**Comment by mrtnhmtz** [comment]
Wrt socio, I just added the required file in the folder for German specific answers: https://github.com/softwaresaved/international-survey/commit/a1d620cf2609a2b34ea11722689bbf51e4c1ea51

**Comment by Oliph** [comment]
* currentEmp11 only when not permanent: Not possible for me to do that because the Canadian wanted a separated list of contracts. 

* prevEmp1 being a single question: Yes it is just to know if we have people from the private sector that comes to academia. 

* A back button: should be put back

* edu2 -- other: I added the option 'other'

* 'mandatory: it is turn on now

* Problem with matrix: That's a side effect of a fix I had to apply. The questions have different conditions, therefore they are not grouped together (it caused blank bullet points before)

* Problem with conditions: seems to be for question that requires a Yes. I still looking at it. It should not be hard to fix

* Href style: Still looking at it

* recog 3 not making sense: Normally now it is "Institution", not "University". I understand the concern about that question. However I think it can be still interesting, not as an isolated question, but in link with the other recogs as it can show different level of recognition between different levels. I don't know how to make it better right now. Open to suggestions.
