### ISSUE TITLE
Editing introductory text

### ISSUE THREAD

**Issue by Oliph** [softwaresaved/international-survey#36]
The big text is too long splitting it into 
* Why
* Who
* Privacy

**Comment by SimonHettrick** [comment]
The purpose of this survey is to collect information about Research Software Engineers (RSEs). These are the people who create the software that is used in research.

# Why did I receive this invitation?

You have received this link because you are a member of the UK RSE Association or you were identified as someone working in an RSE role. There is currently little reliable information about the RSE community, so we have been asked to collect this information to help funders and other research organisations develop policies that will support RSEs. This questionnaire gives you the opportunity to express your views about your current job and give us information about your career path.

Please note that this research is not compulsory and even if you decide to participate you can withdraw at any moment.

# How long will it take?

There are 63 questions in this survey. It takes about 10 minutes to complete.

# Who is responsible for this survey?

This study is conducted by the Software Sustainability Institute. The investigators are Simon Hettrick and Olivier Philippe. The survey is hosted on Limesurvey servers in Germany and respects the provisions of the Data Protection Act. These records are anonymised and access is strictly protected and granted to the main researchers only. The results of the survey will be released publicily but only after they have been processed to ensure that individual respondents can not be identified. The results will be released under a Creative Commons by attribution, non-commercial licence.

If you would like more information about the research or about the data collection, please contact Olivier Philippe.

If you have a concern or would like to make a complaint, please contact Simon Hettrick.

A note on privacy
This survey is anonymous.
The record of your survey responses does not contain any identifying information about you, unless a specific survey question explicitly asked for it. If you used an identifying token to access this survey, please rest assured that this token will not be stored together with your responses. It is managed in a separate database and will only be updated to indicate whether you did (or did not) complete this survey. There is no way of matching identification tokens with survey responses.

**Comment by Oliph** [comment]
Disable the automatic "Show "There are X questions in this survey" in the "Presentation"

**Comment by Oliph** [comment]
done
