### ISSUE TITLE
percEmp2: Adding motivator to accept current position

### ISSUE THREAD

**Issue by Oliph** [softwaresaved/international-survey#38]
* Adding
1. My software will be used
2. I learn new skills
3. Working in an interesting application area

* Changing
* Desire to help researcher -> Desire to advance research
* 'Career opportunities available' -> Opportunity for career advancement

**Comment by SimonHettrick** [comment]
Let's change the question to:

"Rank the following factors dependent on how strongly they influenced your decision to accept your current position?"

1. Desire to advance research (an edit rather than an addition)
2. Opportunity for career advancement (an edit rather than an addition)
3. The salary (an edit rather than an addition)
4. I want to learn new skills

**Comment by Oliph** [comment]
done
